### ISSUE TITLE
Training session in BioCotnainers Hackathon

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/workshops#1]
Dear @bgruening @osallou @rajido and other organizers: 

I have made some major changes in the programme (https://github.com/BioContainers/workshops/blob/master/README.md). It would be great if you give me some feedback about it. 

1- Some people suggested a training session the first day to be able to contribute to BioContainers. I like the idea of a 2-hour session after the talks and in parallel to the metadata session. @osallou are you willing to give this training. 

2- I suggest that you take a deep look to the program an suggest me changes, etc. We will have almost 40 participants that they don't need to be involved in all discussions and we have two rooms that can be used to split into parallel sessions get more from the time we will be in Paris. 

Best Regards 
Yasset

**Comment by osallou** [comment]
@ypriverol , you suggest a training on how to create a Dockerfile for a tool and build/test an image ? and how to add new tools to biocontainers repo via github? I am ok to do so.
I would have liked to participate to metadata session, but this is fine, someone must do the job  ;-)
Regarding my talk "Dockerfile - based BioContainers" , idea would be to present quickly how people can contribute with Dockerfiles, and what we expect in Dockerfiles, then people willing to practice Docker image building would go to the training session, I am right?

I mainly expect to participate to architecture discussion.  I could present my prototype during this session to see if it could fit our needs.

**Comment by ypriverol** [comment]
Thanks, @osallou to support this idea. Definitely, you will be included in the decisions around the metadata. Also, someone from your team should be there, but this training session is really important for the hackathon and the new contributors. We plan to do a wrap-up every session that you can use to give your opinion directly if you were not involved in the discussions. 

I have talked to @bgruening  and We should include into the training both types of containers. If you need any support for the Mulled/Conda containers please let @bgruening know about it, he is more than happy to give you documentation, and materials for it.  

About the architecture discussion. Please be prepared because your ideas are crucial for the future architecture and deployment of the containers.

**Comment by bgruening** [comment]
Hi,

we have already some training materials which can be used as a base here:

Conda, planemo and slides:
https://galaxyproject.github.io/training-material/topics/dev/tutorials/conda/slides.html

Mulled, BioContainers, Galaxy:
https://galaxyproject.github.io/training-material/topics/dev/tutorials/containers/slides.html

**Comment by osallou** [comment]
Ok, though not an expert on conda, can do the job for beginners.

Le dim. 1 oct. 2017 22:01, Björn Grüning <notifications@github.com> a
écrit :

**Comment by ypriverol** [comment]
Great, Thanks, Olivier.
